[workspace]

members = [
    "ds-http-client",
    "fantoir-datasource",
    "language-subtag-registry-datasource",
    "rfc-datasource",
    "opendatasoft-explore-api",
    "sparql-client",
]

resolver = "2"
